---
- name: Install MySQL
  hosts: web
  vars:
    db_root_user: root
    db_root_password: "H0$@m_3142"
    db_name: employee_db
    db_user: omegaimpakt
    db_user_password: "H0$@m_9997"
  tasks:
  - name: Import MySQL GPG Key
    ansible.builtin.rpm_key:
      state: present
      key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
    become: true

  - name: Download MySQL repository RPM
    ansible.builtin.dnf:
      name: https://repo.mysql.com/mysql84-community-release-el9-2.noarch.rpm
      state: present
    become: true

  - name: Install MySQL & dependencies
    ansible.builtin.dnf: name={{ item }} state=installed
    with_items:
    - mysql
    - mysql-server
    - python3-PyMySQL
    - python3-pip-wheel
    - '@Development tools'
    - python3-devel.x86_64
    - python3-setuptools
    become: true

  - name: Stop mysqld service
    ansible.builtin.service:
      name: mysqld
      state: stopped
    become: true

  - name: Set MySQL skip-grant-tables mode
    ansible.builtin.command: >
      systemctl set-environment MYSQLD_OPTS="--skip-grant-tables --skip-networking"
    become: true

  - name: Start mysqld in skip-grant-tables mode
    ansible.builtin.service:
      name: mysqld
      state: started
    become: true

  - name: Reset MySQL root password
    community.mysql.mysql_query:
      login_unix_socket: /var/lib/mysql/mysql.sock
      query:
      - "FLUSH PRIVILEGES;"
      - "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '{{ new_root_password }}';"
      - "FLUSH PRIVILEGES;"
    become: true

  - name: Stop mysqld service after password reset
    ansible.builtin.service:
      name: mysqld
      state: stopped
    become: true

  - name: Unset MySQL environment options
    ansible.builtin.command: systemctl unset-environment MYSQLD_OPTS
    become: true

  - name: Start mysqld service normally
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
    become: true

  - name: Set root password
    community.mysql.mysql_query:
      name: root
      password: "YourRootPassw0rd"
      host: localhost
      login_unix_socket: /var/lib/mysql/mysql.sock

  - name: Create employee_db
    community.mysql.mysql_db:
      login_user: "{{ db_root_user }}"
      login_password: "{{ new_root_password }}"
      name: "{{ db_name }}"
      state: present

  - name: Create MySQL user for localhost
    community.mysql.mysql_user:
      login_user: "{{ db_root_user }}"
      login_password: "{{ new_root_password }}"
      name: "{{ db_user }}"
      host: "localhost"
      password: "{{ db_user_password }}"
      plugin: mysql_native_password
      priv: "*.*:ALL"
      state: present

  - name: Create database user for remote access
    community.mysql.mysql_user:
      login_user: "{{ db_root_user }}"
      login_password: "{{ new_root_password }}"
      name: "{{ db_user }}"
      host: "%"
      password: "{{ db_user_password }}"
      plugin: mysql_native_password
      priv: "*.*:ALL"
      state: present

  - name: Install Flask and its dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      state: present
    with_items:
    - flask
    - flask-mysql

  - name: Cloning the repository
    ansible.builtin.git:
      repo: 'https://github.com/mmumshad/simple-webapp.git'
      dest: /home/omegaimpakt/simple-webapp

  - name: Starting the web server
    ansible.builtin.shell: flask --app /home/omegaimpakt/simple-webapp/app.py run --debug --host=0.0.0.0
